import array as arr
snack1 = {"chips", "candy", "chocolate", "candy"}
snack2 = {"cookies", "coke", "candy", "juice", "apple", "cookies"}
print(f"Snack box 1: {snack1}")
print(f"Snack box 2: {snack2}")
snack1.add("banana")
print(f"Updated snack box 1: {snack1}")
common = snack1.intersection(snack2)
print(f"The common snacks are: {common}")
stock = arr.array("i", [2, 5, 10, 9, 7, 4])
print(f"Snack count array: {stock}")
stock.insert(0,3)
stock.append(11)
print(f"Array after addition of items: {stock}")
count_of_num = stock.count(2)
print(f"2 appears {count_of_num} time(s)")
stock.reverse()
print(f"The reversed array: {stock}")
stock.reverse()
print("=======FINAL SNACK SUMMARY==========")
print(f"Snack box 1: {snack1}")
print(f"Snack box 2: {snack2}")
print(f"Shared snacks: {common}")
print(f"The amount of each snack: {stock}")
print("====================================")