habit_info = ("Reading", False, 9, 50)
print(habit_info)
weekly_habits = (1, 0, 0, 1, 1, 1)
print(weekly_habits)
print(f"There are {len(weekly_habits)} days stored in weekly habits")
print(f"2nd day: {weekly_habits[1]}")
print(f"1st day: {habit_info[0]}")
print(f"First four days: {weekly_habits[0:5]}")
print(f"2nd to 3rd day: {habit_info[1:3]}")
weekly_habits += (1,)
completed = weekly_habits.count(1)
missed = weekly_habits.count(0)
print(f"Completed days: {completed}")
print(f"Missed days: {missed}")
